//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuLuBWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyInfo
    {
        public int Id { get; set; }
        public string accountNo { get; set; }
        public System.DateTime dealDate { get; set; }
        public string dealType { get; set; }
        public double dealMoney { get; set; }
        public double balance { get; set; }
    }
}
