//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJ
    {
        public int AutoID { get; set; }
        public string XueHao { get; set; }
        public string KCBianMa { get; set; }
        public string XueNianXueQi { get; set; }
        public string XiuDuLeiBie { get; set; }
        public Nullable<int> ChengJi { get; set; }
        public string BeiZhu { get; set; }
    }
}
