//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string XueHao { get; set; }
        public string XingMing { get; set; }
        public string XingBie { get; set; }
        public Nullable<System.DateTime> ChuShengRiQi { get; set; }
        public byte[] ZhaoPian { get; set; }
    }
}
